---
- name: obtenir des informations sur la memoire Setup
  hosts: all
  tasks:
    - debug: var=ansible_memory_mb
    - debug: msg="total RAM is {{ ansible_memory_mb.real.total }}"
    - assert:
        that:
         - ansible_memory_mb.real.total >= 4096
        fail_msg: "'ansible_memory_mb.real.total' is too low"
        success_msg: "'ansible_memory_mb.real.total' is ok"


