---
- hosts: centos_remote_a
  become: true
  gather_facts: no
  tasks:
    - name: data container
      docker_container:
        name: mydata
        image: busybox
        state: present
        volumes:
        - /data
    - name: install git
      docker_container:
        name: redis
        image: redis
        command: redis-server --appendonly yes
        state: started
        expose:
        - 6379
        volumes_from:
        - mydata