---
- name: Create MOTD file
  hosts: all
  vars:
      text_message: " Ansible @ SIGI"
  tasks:
    - name: copy template file
      template:
        src: motd.j2
        dest: /etc/motd
  tags:
    - motd_config




