---
- hosts: all
  become: true
  vars:
    motd_value: "{{ lookup('file', '/etc/motd') }}"
  tasks:
    - name: Uppercase message
      debug:
        msg: "{{ motd_value.stdout | upper }}"
    - name: Lower Message
      debug:
        msg: "{{ motd_value.stdout | lower }}"
    - name: Funny message
      debug:
        msg: "{{ motd_value.stdout | a_filter}}"