---
- hosts: all
  become: true
  tasks:
    - name: cat file
      command: cat /etc/motd
      register: result
    - name: Uppercase message
      debug:
        msg: "{{ result.stdout | upper }}"
    - name: Lower Message
      debug:
        msg: "{{ result.stdout | lower }}"
    - name: Funny message
      debug:
        msg: "{{ result.stdout | a_filter}}"