---
# resolved : https://bugzilla.redhat.com/show_bug.cgi?id=1539142
#
- hosts: all
  vars:
    myuser: justin
  tasks:
    - name: add user {{myuser}}
      become: true
      user:
        name: "{{ myuser }}"
        shell: /bin/bash
        password: "{{ '12345678' | password_hash('sha512') }}"
        groups: wheel
        append: yes
      tags:
        - ceph
    - name: Create a directory for ssh
      become: true
      file:
        path: "/home/{{ myuser }}/.ssh"
        owner: "{{ myuser}}"
        group: "{{ myuser}}"
        state: directory
        mode: '0700'
      tags:
        - dir
    - name: create a file know_authorized
      become: true
      file:
        path: "/home/{{ myuser }}/.ssh/authorized_keys"
        owner: "{{ myuser}}"
        group: "{{ myuser}}"
        state: touch
        mode: '0600'
- hosts: ceph
  become: true
  vars:
    myuser: justin
  tasks:
    - name: create ssh key on admin user myuser
      delegate_to: ceph-controller
      openssh_keypair:
        path: "/home/{{myuser}}/.ssh/id_rsa"
        owner: "{{ myuser }}"
        group: "{{ myuser }}"
      register: ssh_key
      tags:
        - key
    - name: add public key
      lineinfile:
        path: "/home/{{ myuser }}/.ssh/authorized_keys"
        state: present
        line: "{{ssh_key['public_key'] }}"
      tags:
        - val
- hosts: admin
  become: true
  roles:
    - role: role.docker
      tags: docker
