---
- hosts: all
  tasks:
  - name: get a token
    command: openssl genrsa -out Dev.key 2048
    register: my_token
  - name: get a hash
    shell: echo {{ '12345678' | hash('md5') }}
    register: my_hash
  - name: add new node into runtime inventory
    add_host:
       name: "dummy"
       token: "{{ my_token }}"
       hash: "{{ my_hash }}"
       ip_address: "192.168.1.10"

- hosts: centosdocker
  tasks:
    - name: create a file
      file: src=/tmp/values state=touch
    - name: add values
      blockinfile:
        path: /tmp/values
        block: |
          {{hostvars['dummy']['token']}}
          {{hostvars['dummy']['hash']}}
          {{hostvars['dummy']['ip_address']}}

